"use client";

import { useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { ExplainPanel } from "@/components/app/explain-panel";
import type { Report, ReportAccount, ReportCollection, ReportInquiry } from "@/lib/supabase/types";
import {
  accountPill,
  accountSubtitle,
  confidenceStars,
  deriveScoreFactors,
  formatDate,
  formatMoney,
  formatPercent,
  generateExecutiveSummary,
  impactTone,
  inquiryPill,
  utilizationTone,
  validationStatusLabel,
  validationStatusTone,
  type Tone,
} from "@/lib/report-derivations";

const mono = "font-[family-name:var(--font-jetbrains-mono)]";

type Section =
  | "overview"
  | "accounts"
  | "collections"
  | "inquiries"
  | "recs"
  | "letters"
  | "timeline";

function toneText(tone: Tone) {
  if (tone === "bad") return "text-[#c23e3e]";
  if (tone === "warn") return "text-[#c2731a]";
  if (tone === "good") return "text-[var(--teal-deep)]";
  return "text-[var(--ink)]";
}

function tonePill(tone: Tone) {
  if (tone === "bad") return "bg-[#fbecec] text-[#a33232]";
  if (tone === "warn") return "bg-[#fdf3e7] text-[#9a6314]";
  if (tone === "good") return "bg-[#e6f5ef] text-[var(--teal-deep)]";
  return "bg-[#eef2f7] text-[var(--muted)]";
}

function InfoDot({ onClick }: { onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      aria-label="Explain this"
      className="ml-2 flex h-[18px] w-[18px] flex-none cursor-pointer items-center justify-center rounded-full bg-[#e6f5ef] text-[11px] font-bold text-[var(--teal-deep)]"
    >
      i
    </button>
  );
}

const RECOMMENDATION_CATEGORY: Record<string, string> = {
  collection: "COLLECTIONS",
  credit_card: "PAYMENT STRATEGY",
  retail_card: "PAYMENT STRATEGY",
  auto_loan: "CREDIT BUILDING",
  student_loan: "CREDIT BUILDING",
  mortgage: "CREDIT BUILDING",
  other: "CREDIT BUILDING",
};

const IMPACT_RANK: Record<string, number> = { high: 3, medium: 2, low: 1 };

export function ReportViewer({
  report,
  accounts,
  collections,
  inquiries,
  reportLabel,
  reportSub,
}: {
  report: Report;
  accounts: ReportAccount[];
  collections: ReportCollection[];
  inquiries: ReportInquiry[];
  reportLabel: string;
  reportSub: string;
}) {
  const [section, setSection] = useState<Section>("overview");
  const [selectedAccount, setSelectedAccount] = useState<number | null>(null);
  const [explainOpen, setExplainOpen] = useState<string | null>(null);
  const [scriptTab, setScriptTab] = useState(0);
  const [glossaryTerm, setGlossaryTerm] = useState<string | null>(null);

  function goSection(s: Section) {
    setSection(s);
    setSelectedAccount(null);
  }

  const sel = selectedAccount != null ? accounts[selectedAccount] : null;

  const letters = collections.map((c) => ({
    label: c.agency_name ?? "Collection",
    title: `Debt Validation Letter — ${c.agency_name ?? "Unknown agency"}`,
    sub: c.ai_summary
      ? "Educational explanation & sample validation letter · generated by Clarity AI"
      : "Not yet analyzed",
    body: c.ai_summary,
  }));
  const activeScript = letters[scriptTab] ?? null;

  const executiveSummary = generateExecutiveSummary(report, accounts, collections);
  const scoreWhy = deriveScoreFactors(accounts, collections);

  const recommendations = accounts
    .filter((a) => a.recommended_action)
    .sort(
      (a, b) =>
        (IMPACT_RANK[b.impact ?? ""] ?? 0) - (IMPACT_RANK[a.impact ?? ""] ?? 0) ||
        (b.confidence ?? 0) - (a.confidence ?? 0),
    )
    .map((a) => ({
      category: RECOMMENDATION_CATEGORY[a.type ?? "other"] ?? "CREDIT BUILDING",
      title: a.recommended_action as string,
      detail: a.ai_summary ?? "",
      confidence: confidenceStars(a.confidence),
    }));

  type TimelineEvent = { date: string; title: string; detail: string; tone: Tone; sortDate: string };

  const timelineEvents: TimelineEvent[] = [];
  if (report.report_date) {
    timelineEvents.push({
      date: formatDate(report.report_date, { month: "short", year: "numeric" }).toUpperCase(),
      title: `Report ${report.status === "analyzed" ? "analyzed" : "uploaded"} — score ${report.credit_score ?? "—"}`,
      detail: `${accounts.length} account${accounts.length === 1 ? "" : "s"} on file.`,
      tone: "neutral",
      sortDate: report.report_date,
    });
  }
  for (const c of collections) {
    if (!c.opened_date) continue;
    timelineEvents.push({
      date: formatDate(c.opened_date, { month: "short", year: "numeric" }).toUpperCase(),
      title: `Collection opened — ${c.agency_name ?? "Unknown agency"} (${formatMoney(c.amount)})`,
      detail: c.original_creditor ? `Original creditor: ${c.original_creditor}.` : "",
      tone: "bad",
      sortDate: c.opened_date,
    });
  }
  timelineEvents.sort((a, b) => new Date(b.sortDate).getTime() - new Date(a.sortDate).getTime());

  return (
    <div className="flex min-h-screen">
      {/* inner rail */}
      <div className="sticky top-0 h-screen w-[208px] flex-none border-r border-[var(--border)] bg-white p-[22px_10px]">
        <div className="px-3 pb-3.5">
          <div className="text-sm font-bold">{reportLabel}</div>
          <div className="text-[11.5px] text-[#8fa3ba]">{reportSub}</div>
        </div>
        <div className="flex flex-col gap-0.5">
          {(
            [
              { key: "overview", label: "Overview" },
              { key: "accounts", label: "Accounts", count: accounts.length },
              { key: "collections", label: "Collections", count: collections.length },
              { key: "inquiries", label: "Inquiries", count: inquiries.length },
              { key: "recs", label: "Recommendations", count: recommendations.length },
              { key: "letters", label: "Letters", count: letters.length },
              { key: "timeline", label: "Timeline" },
            ] as { key: Section; label: string; count?: number }[]
          ).map((n) => (
            <button
              key={n.key}
              onClick={() => goSection(n.key)}
              className={cn(
                "flex items-center rounded-[9px] px-3 py-2.5 text-left text-[13px] font-semibold",
                section === n.key ? "bg-[#eef4f1] text-[var(--teal-deep)]" : "text-[#3d5068]",
              )}
            >
              {n.label}
              {n.count != null && (
                <span className={cn(mono, "ml-auto text-[11px] text-[#8fa3ba]")}>{n.count}</span>
              )}
            </button>
          ))}
          <Link
            href={`/reports/${report.id}/pdf-report`}
            className="flex items-center rounded-[9px] px-3 py-2.5 text-[13px] font-semibold text-[#3d5068]"
          >
            PDF Export
          </Link>
        </div>
      </div>

      {/* content */}
      <div className="max-w-[900px] flex-1 min-w-0 px-9 pb-[72px] pt-7">
        {section === "overview" && (
          <>
            <h1 className="m-0 mb-[18px] text-[22px] tracking-[-0.02em]">Overview</h1>
            <div className="mb-3.5 rounded-2xl border border-[var(--border)] bg-white p-6">
              <div className="mb-2.5 text-[11px] font-bold tracking-[0.08em] text-[var(--teal)]">
                EXECUTIVE SUMMARY
              </div>
              <p className="m-0 text-[14.5px] leading-[1.7]">{executiveSummary}</p>
            </div>
            {scoreWhy.length > 0 ? (
              <div className="grid grid-cols-2 gap-3">
                {scoreWhy.map((w, i) => (
                  <div
                    key={i}
                    className="flex gap-3 rounded-[14px] border border-[var(--border)] bg-white p-4"
                  >
                    <div
                      className={cn(
                        "flex h-[26px] w-[26px] flex-none items-center justify-center rounded-full text-sm font-bold",
                        w.positive
                          ? "bg-[#e6f5ef] text-[var(--teal-deep)]"
                          : "bg-[#fbecec] text-[#a33232]",
                      )}
                    >
                      {w.sign}
                    </div>
                    <div>
                      <div className="text-[13.5px] font-semibold">{w.title}</div>
                      <div className="mt-0.5 text-[12.5px] leading-[1.5] text-[var(--muted)]">
                        {w.detail}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="rounded-[14px] border border-[var(--border)] bg-white p-4 text-[13px] text-[var(--muted)]">
                Not enough data yet to break down score factors.
              </div>
            )}
          </>
        )}

        {section === "accounts" && !sel && (
          <>
            <h1 className="m-0 mb-1.5 text-[22px] tracking-[-0.02em]">Accounts</h1>
            <div className="mb-[18px] text-[13px] text-[var(--muted)]">
              Click any account for its full analysis page.
            </div>
            {accounts.length === 0 && (
              <div className="rounded-[14px] border border-[var(--border)] bg-white p-4 text-[13px] text-[var(--muted)]">
                No accounts found on this report.
              </div>
            )}
            <div className="flex flex-col gap-2.5">
              {accounts.map((a, i) => {
                const pill = accountPill(a);
                const uTone = utilizationTone(a.utilization);
                return (
                  <button
                    key={a.id}
                    onClick={() => setSelectedAccount(i)}
                    className="grid grid-cols-[1.5fr_.7fr_.6fr_.8fr_auto] items-center gap-3.5 rounded-[14px] border border-[var(--border)] bg-white px-5 py-4 text-left hover:border-[var(--teal)]"
                  >
                    <div>
                      <div className="text-sm font-bold">{a.name}</div>
                      <div className="text-[11.5px] text-[#8fa3ba]">{accountSubtitle(a)}</div>
                    </div>
                    <div>
                      <div className="text-[10.5px] font-semibold text-[#8fa3ba]">BALANCE</div>
                      <div className={cn(mono, "mt-0.5 text-[13.5px] font-semibold")}>
                        {formatMoney(a.balance)}
                      </div>
                    </div>
                    <div>
                      <div className="text-[10.5px] font-semibold text-[#8fa3ba]">UTIL.</div>
                      <div className={cn(mono, "mt-0.5 text-[13.5px] font-semibold", toneText(uTone))}>
                        {formatPercent(a.utilization)}
                      </div>
                    </div>
                    <div>
                      <span className={cn("rounded-full px-2.5 py-1 text-[10.5px] font-bold", tonePill(pill.tone))}>
                        {pill.label}
                      </span>
                    </div>
                    <div className="text-[15px] text-[#8fa3ba]">›</div>
                  </button>
                );
              })}
            </div>
          </>
        )}

        {section === "accounts" && sel && (
          <>
            <button
              onClick={() => setSelectedAccount(null)}
              className="mb-3.5 text-[13px] font-semibold text-[var(--teal)]"
            >
              ← All accounts
            </button>
            <div className="mb-4 flex items-start justify-between">
              <div>
                <h1 className="m-0 mb-1 text-2xl tracking-[-0.02em]">{sel.name}</h1>
                <div className="text-[13px] text-[var(--muted)]">{accountSubtitle(sel)}</div>
              </div>
              <span className={cn("rounded-full px-2.5 py-1 text-[10.5px] font-bold", tonePill(accountPill(sel).tone))}>
                {accountPill(sel).label}
              </span>
            </div>
            <div className="mb-3.5 grid grid-cols-5 gap-2.5">
              <div className="rounded-[13px] border border-[var(--border)] bg-white p-3.5">
                <div className="text-[10.5px] font-semibold text-[#8fa3ba]">BALANCE</div>
                <div className={cn(mono, "mt-1.5 text-[17px] font-semibold")}>{formatMoney(sel.balance)}</div>
              </div>
              <div className="rounded-[13px] border border-[var(--border)] bg-white p-3.5">
                <div className="text-[10.5px] font-semibold text-[#8fa3ba]">LIMIT</div>
                <div className={cn(mono, "mt-1.5 text-[17px] font-semibold")}>{formatMoney(sel.credit_limit)}</div>
              </div>
              <div className="rounded-[13px] border border-[var(--border)] bg-white p-3.5">
                <div className="flex items-center text-[10.5px] font-semibold text-[#8fa3ba]">
                  UTILIZATION
                  <InfoDot onClick={() => setGlossaryTerm("utilization")} />
                </div>
                <div
                  className={cn(mono, "mt-1.5 text-[17px] font-semibold", toneText(utilizationTone(sel.utilization)))}
                >
                  {formatPercent(sel.utilization)}
                </div>
              </div>
              <div className="rounded-[13px] border border-[var(--border)] bg-white p-3.5">
                <div className="text-[10.5px] font-semibold text-[#8fa3ba]">HISTORY</div>
                <div className="mt-[7px] text-[13px] font-semibold">{sel.payment_history ?? "—"}</div>
              </div>
              <div className="rounded-[13px] border border-[var(--border)] bg-white p-3.5">
                <div className="text-[10.5px] font-semibold text-[#8fa3ba]">SCORE IMPACT</div>
                <div className={cn("mt-[7px] text-[13px] font-bold", toneText(impactTone(sel.impact)))}>
                  {sel.impact ? sel.impact[0].toUpperCase() + sel.impact.slice(1) : "—"}
                </div>
              </div>
            </div>
            <div className="mb-3.5 rounded-2xl border border-[var(--border)] bg-white p-[22px]">
              <div className="mb-2.5 flex items-center gap-2">
                <div className="flex h-[22px] w-[22px] items-center justify-center rounded-[7px] bg-gradient-to-br from-[var(--teal)] to-[var(--mint)]">
                  <div className="h-2 w-2 rounded-full bg-white" />
                </div>
                <span className="text-[11px] font-bold tracking-[0.08em] text-[var(--teal)]">
                  CLARITY AI SUMMARY
                </span>
              </div>
              <p className="m-0 text-[14.5px] leading-[1.7]">
                {sel.ai_summary ?? "Analysis for this account hasn't been generated yet."}
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="rounded-2xl bg-[#e6f5ef] p-5">
                <div className="mb-2 text-[11px] font-bold tracking-[0.06em] text-[var(--teal-deep)]">
                  RECOMMENDED ACTION
                </div>
                <div className="text-base font-bold">{sel.recommended_action ?? "No action recommended yet"}</div>
              </div>
              <div className="rounded-2xl border border-[var(--border)] bg-white p-5">
                <div className="mb-2 flex justify-between">
                  <span className="text-[11px] font-bold tracking-[0.06em] text-[var(--muted)]">
                    SCORE IMPACT
                  </span>
                  <span className={cn("text-[13px] font-bold", toneText(impactTone(sel.impact)))}>
                    {sel.impact ? sel.impact[0].toUpperCase() + sel.impact.slice(1) : "—"}
                  </span>
                </div>
                <div className="mb-2 flex items-center justify-between">
                  <span className="text-[11px] font-bold tracking-[0.06em] text-[var(--muted)]">
                    AI CONFIDENCE
                  </span>
                  <span className="text-sm tracking-[2px] text-[#e0a23a]">{confidenceStars(sel.confidence)}</span>
                </div>
              </div>
            </div>
          </>
        )}

        {section === "collections" && (
          <>
            <h1 className="m-0 mb-[18px] flex items-center text-[22px] tracking-[-0.02em]">
              Collections
              <InfoDot onClick={() => setGlossaryTerm("collection")} />
            </h1>
            {collections.length === 0 && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 text-[13.5px] text-[var(--muted)]">
                No collections on this report — nice work.
              </div>
            )}
            <div className="flex flex-col gap-3.5">
              {collections.map((c) => (
                <div key={c.id} className="rounded-2xl border border-[#f0d4d4] bg-white p-6">
                  <div className="mb-3.5 flex items-start justify-between">
                    <div>
                      <div className="text-[17px] font-bold">{c.agency_name ?? "Unknown agency"}</div>
                      <div className="mt-0.5 text-[12.5px] text-[var(--muted)]">
                        Original: {c.original_creditor ?? "—"} · {formatMoney(c.amount)} · opened{" "}
                        {formatDate(c.opened_date, { month: "short", year: "numeric" })} · falls off{" "}
                        {formatDate(c.falls_off_date, { month: "short", year: "numeric" })}
                      </div>
                    </div>
                    <span
                      className={cn(
                        "rounded-full px-3 py-1.5 text-[11px] font-bold",
                        tonePill(validationStatusTone(c.validation_status)),
                      )}
                    >
                      {validationStatusLabel(c.validation_status)}
                    </span>
                  </div>
                  <button
                    onClick={() => setExplainOpen((v) => (v === c.id ? null : c.id))}
                    className="flex w-full items-center justify-between rounded-xl bg-[#f8fafc] px-4 py-3.5 hover:bg-[#eef4f1]"
                  >
                    <span className="text-sm font-semibold">What does this mean?</span>
                    <span className="font-bold text-[var(--teal)]">{explainOpen === c.id ? "−" : "+"}</span>
                  </button>
                  {explainOpen === c.id && (
                    <div className="mt-3 border-l-[3px] border-[var(--teal)] py-1 pl-4">
                      <div className="mb-2 flex items-center gap-[7px]">
                        <div className="h-[18px] w-[18px] rounded-[6px] bg-gradient-to-br from-[var(--teal)] to-[var(--mint)]" />
                        <span className="text-[11px] font-bold tracking-[0.08em] text-[var(--teal)]">
                          CLARITY AI EXPLAINS
                        </span>
                      </div>
                      <p className="m-0 mb-2.5 text-sm leading-[1.7] text-[#22354d] last:mb-3">
                        {c.ai_summary ??
                          "A collection means your original debt was sold to a collection agency after going unpaid. Before paying anything, you have a legal right to demand written validation."}
                      </p>
                      <div className="flex gap-2">
                        <button
                          onClick={() => goSection("letters")}
                          className="rounded-[9px] bg-[var(--teal)] px-[15px] py-2 text-[12.5px] font-semibold text-white hover:bg-[var(--teal-deep)]"
                        >
                          Open Validation Letter
                        </button>
                        <Link
                          href="/chat"
                          className="rounded-[9px] border-[1.5px] border-[#dbe3ec] px-[15px] py-2 text-[12.5px] font-semibold hover:border-[var(--navy)]"
                        >
                          Ask a Follow-up
                        </Link>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </>
        )}

        {section === "inquiries" && (
          <>
            <h1 className="m-0 mb-[18px] flex items-center text-[22px] tracking-[-0.02em]">
              Hard Inquiries
              <InfoDot onClick={() => setGlossaryTerm("inquiry")} />
            </h1>
            {inquiries.length === 0 ? (
              <div className="rounded-xl bg-[#e6f5ef] px-[18px] py-3.5 text-[13px] leading-[1.6] text-[#22354d]">
                ✓ <strong>No hard inquiries on this report.</strong>
              </div>
            ) : (
              <div className="flex flex-col gap-2.5">
                {inquiries.map((q) => {
                  const pill = inquiryPill(q.impact);
                  return (
                    <div
                      key={q.id}
                      className="flex items-center justify-between rounded-[14px] border border-[var(--border)] bg-white px-[22px] py-4"
                    >
                      <div>
                        <div className="text-sm font-bold">{q.lender_name ?? "Unknown lender"}</div>
                        <div className="text-xs text-[#8fa3ba]">
                          {q.inquiry_type ?? "Inquiry"} · {formatDate(q.inquiry_date, { month: "short", year: "numeric" })}
                        </div>
                      </div>
                      <span className={cn("rounded-full px-[11px] py-1 text-[11px] font-bold", tonePill(pill.tone))}>
                        {pill.label}
                      </span>
                    </div>
                  );
                })}
                <div className="rounded-xl bg-[#e6f5ef] px-[18px] py-3.5 text-[13px] leading-[1.6] text-[#22354d]">
                  ✓ <strong>No action needed.</strong> Inquiries stop affecting your score after 12
                  months and fall off after 24.
                </div>
              </div>
            )}
          </>
        )}

        {section === "recs" && (
          <>
            <h1 className="m-0 mb-[18px] text-[22px] tracking-[-0.02em]">Recommendations</h1>
            {recommendations.length === 0 && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 text-[13.5px] text-[var(--muted)]">
                No recommendations generated for this report yet.
              </div>
            )}
            <div className="flex flex-col gap-3">
              {recommendations.map((r, i) => (
                <div
                  key={i}
                  className="grid grid-cols-[1fr_auto] gap-[18px] rounded-2xl border border-[var(--border)] bg-white p-[22px]"
                >
                  <div>
                    <div className="mb-1.5 text-[11px] font-bold tracking-[0.06em] text-[var(--teal)]">
                      {r.category}
                    </div>
                    <div className="mb-1.5 text-[15.5px] font-bold">{r.title}</div>
                    <div className="max-w-[560px] text-[13.5px] leading-[1.6] text-[var(--muted)]">
                      {r.detail}
                    </div>
                  </div>
                  <div className="flex-none text-right">
                    <div className="mb-1 text-[10.5px] font-bold text-[#8fa3ba]">CONFIDENCE</div>
                    <div className="text-sm tracking-[2px] text-[#e0a23a]">{r.confidence}</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {section === "letters" && (
          <>
            <h1 className="m-0 mb-3.5 text-[22px] tracking-[-0.02em]">Letters &amp; Scripts</h1>
            {letters.length === 0 ? (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 text-[13.5px] text-[var(--muted)]">
                No collections on this report — no validation letters needed.
              </div>
            ) : (
              <>
                <div className="mb-4 flex flex-wrap gap-2">
                  {letters.map((s, i) => (
                    <button
                      key={`${s.label}-${i}`}
                      onClick={() => setScriptTab(i)}
                      className={cn(
                        "rounded-full border-[1.5px] px-[15px] py-2.5 text-[12.5px] font-semibold",
                        scriptTab === i
                          ? "border-[var(--navy)] bg-[var(--navy)] text-white"
                          : "border-[#dbe3ec] bg-white text-[#3d5068]",
                      )}
                    >
                      {s.label}
                    </button>
                  ))}
                </div>
                {activeScript && (
                  <div className="rounded-2xl border border-[var(--border)] bg-white p-6">
                    <div className="mb-3.5 flex items-center justify-between">
                      <div>
                        <div className="text-base font-bold">{activeScript.title}</div>
                        <div className="mt-0.5 text-[12.5px] text-[var(--muted)]">{activeScript.sub}</div>
                      </div>
                      <button
                        disabled={!activeScript.body}
                        className="rounded-[9px] border-[1.5px] border-[#dbe3ec] bg-white px-3.5 py-2 text-[12.5px] font-semibold hover:border-[var(--navy)] disabled:opacity-40"
                      >
                        Copy
                      </button>
                    </div>
                    {activeScript.body ? (
                      <div className={cn(mono, "whitespace-pre-line rounded-[13px] bg-[#f8fafc] p-[22px] text-[13px] leading-[1.8] text-[#22354d]")}>
                        {activeScript.body}
                      </div>
                    ) : (
                      <div className="rounded-[13px] bg-[#f8fafc] p-[22px] text-[13px] italic leading-[1.8] text-[var(--muted)]">
                        Not yet analyzed — this letter will appear here once Clarity AI finishes
                        analyzing your report.
                      </div>
                    )}
                  </div>
                )}
              </>
            )}
          </>
        )}

        {section === "timeline" && (
          <>
            <h1 className="m-0 mb-[18px] text-[22px] tracking-[-0.02em]">Timeline</h1>
            {timelineEvents.length === 0 && (
              <div className="rounded-2xl border border-[var(--border)] bg-white p-6 text-[13.5px] text-[var(--muted)]">
                No timeline events yet.
              </div>
            )}
            <div className="flex flex-col">
              {timelineEvents.map((t, i) => (
                <div key={i} className="grid grid-cols-[36px_1fr] gap-4">
                  <div className="flex flex-col items-center">
                    <div
                      className={cn(
                        "h-3.5 w-3.5 flex-none rounded-full",
                        t.tone === "good" && "bg-[var(--teal)]",
                        t.tone === "bad" && "bg-[#d05252]",
                        t.tone === "neutral" && "bg-[#c7d2df]",
                      )}
                    />
                    {i < timelineEvents.length - 1 && (
                      <div className="my-1 w-0.5 flex-1 bg-[var(--border)]" />
                    )}
                  </div>
                  <div className="pb-[22px]">
                    <div className={cn(mono, "text-[11.5px] font-bold text-[#8fa3ba]")}>{t.date}</div>
                    <div className="mt-[3px] text-[14.5px] font-bold">{t.title}</div>
                    <div className="mt-0.5 text-[13px] leading-[1.55] text-[var(--muted)]">{t.detail}</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>

      <ExplainPanel term={glossaryTerm} onClose={() => setGlossaryTerm(null)} />
    </div>
  );
}
