import { monoFontFamily } from "../fonts";
import type { PdfReportData } from "../report-data";

// P1 COVER — no footer (cover page is exempt from the running footer).
export function Page01Cover({ data }: { data: PdfReportData }) {
  return (
    <section
      className="page"
      id="p1"
      data-screen-label="PDF Cover"
      style={{
        background: "linear-gradient(165deg,#081527 0%,#0b1f3a 55%,#134066 100%)",
        color: "#fff",
        padding: "64px 64px 48px",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 11 }}>
        <div
          style={{
            width: 34,
            height: 34,
            borderRadius: 10,
            background: "linear-gradient(135deg,#0e9f77,#2ee6a8)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#fff" }} />
        </div>
        <span style={{ fontWeight: 700, fontSize: 19, letterSpacing: "-.01em" }}>Credit Clarity</span>
      </div>

      <div style={{ marginTop: 110 }}>
        <div
          style={{
            fontSize: 13,
            fontWeight: 700,
            letterSpacing: ".14em",
            color: "#5bd6a9",
            marginBottom: 14,
          }}
        >
          PERSONAL CREDIT ANALYSIS &amp; ACTION PLAN
        </div>
        <div style={{ fontSize: 46, fontWeight: 700, letterSpacing: "-.03em", lineHeight: 1.08 }}>
          {data.personName}
        </div>
        <div style={{ fontSize: 15, color: "#b9c8da", marginTop: 14 }}>
          Prepared from your {data.bureauName} report · {data.reportDateLabel}
        </div>
      </div>

      <div style={{ display: "flex", gap: 16, marginTop: 56 }}>
        <div
          style={{
            background: "rgba(255,255,255,.06)",
            border: "1px solid rgba(255,255,255,.12)",
            borderRadius: 16,
            padding: "22px 28px",
          }}
        >
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".1em", color: "#8fa3ba" }}>
            CREDIT SCORE
          </div>
          <div style={{ fontFamily: monoFontFamily, fontSize: 42, fontWeight: 600, marginTop: 6 }}>
            {data.creditScore ?? "—"}
          </div>
          <div style={{ fontSize: 12, color: "#b9c8da", fontWeight: 600 }}>{data.creditScoreBand}</div>
        </div>
        <div
          style={{
            background: "rgba(255,255,255,.06)",
            border: "1px solid rgba(255,255,255,.12)",
            borderRadius: 16,
            padding: "22px 28px",
          }}
        >
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".1em", color: "#8fa3ba" }}>
            CLARITY SCORE
          </div>
          <div style={{ fontFamily: monoFontFamily, fontSize: 42, fontWeight: 600, marginTop: 6 }}>
            {data.clarityScore ?? "—"}
            <span style={{ fontSize: 20, color: "#8fa3ba" }}>/100</span>
          </div>
          <div style={{ fontSize: 12, color: "#b9c8da" }}>{data.clarityScoreDesc}</div>
        </div>
      </div>

      <div style={{ marginTop: "auto" }}>
        <div
          style={{
            borderTop: "1px solid rgba(255,255,255,.14)",
            paddingTop: 18,
            fontSize: 11.5,
            color: "#8fa3ba",
            lineHeight: 1.7,
            maxWidth: 520,
          }}
        >
          CONFIDENTIAL — prepared exclusively for {data.personName}. This is an educational
          analysis generated by Clarity AI. It is not legal, financial, or credit repair
          advice, and the Credit Clarity Score is not a FICO® or VantageScore® credit
          score.
        </div>
      </div>
    </section>
  );
}
