// Shared footer used on every report page except the cover (page 1).
// Product rule (BUILD.md): this exact footer text must appear on every
// report page: "Educational Report · Generated by Clarity AI · Not legal,
// financial, or credit repair advice".
export function PageFooter({ page, total = 13 }: { page: number; total?: number }) {
  return (
    <div
      style={{
        marginTop: "auto",
        display: "flex",
        justifyContent: "space-between",
        fontSize: 9.5,
        color: "#8fa3ba",
        paddingTop: 16,
      }}
    >
      <span>
        Educational Report · Generated by Clarity AI · Not legal, financial, or
        credit repair advice
      </span>
      <span>
        Page {page} of {total}
      </span>
    </div>
  );
}
